name: CFAbsoluteTimeMocking
targets:
    CFAbsoluteTimeMocking:
        type: library.dynamic
        platform: iOS
        sources:
            - path: CFAbsoluteTimeMocking
              excludes:
                  - private/.*
            - path: CFAbsoluteTimeMocking/private
              headerVisibility: private
